---
- hosts: db
  tasks:
    - name: Include the secret file that contains db password 
      include_vars: secret.yml

    - name: copy the db repo from local folder then install the repo 
      become: yes
      copy: src=~/cit-360/ansible/db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644
           

    - name: install the clinet that will communicate with the relational db 
      become: yes
      package: name=MariaDB-client update_cache=yes state=present
     
    - name: unpack the db.tgz and show all information 
      become: yes
      unarchive: src=db/db.tgz dest=~/ mode=0777
       
    - name: Make database by sending the script and other instances to the relational db to host the data
      become: yes
      command: ./make_databases.sh "{{ db_password }}" tf-20161211133654724890400kyp.cke2tagpqykm.us-west-2.rds.amazonaws.com chdir=~/db
      ignore_errors: True
