---
- hosts: web
  vars:
    server_name: curriculum
    service_name: curriculum
    service_version: 1.0
    app_env: test
    app_key: QujjaJs3fxwtnTl7FiqhEEn1ACkf7YZW
    db_host: tf-20161211133654724890400kyp.cke2tagpqykm.us-west-2.rds.amazonaws.com 
    db_database: curriculum
    db_username: curriculum
    db_port: 3306
    service_dir: /usr/share/nginx/{{ service_name }}
  tasks:
    - name: Include Secret file so that it can access db using db password which is contained in secret file 
      include_vars: secret.yml

    - name: Install the epe-release repository 
      become: yes
      yum: name=epel-release update_cache=yes state=present

    - name: This will install php version 5.4 by using shell yum command 
      become: yes
      shell: yes | yum install php54 php54-fpm php54-ldap php54-mbstring php54-mcrypt php54-pdo

    - name: this will install nginx as well as install updates as well 
      become: yes
      yum: name=nginx update_cache=yes state=present
      register: nginx_install
    
    - name: Install the composer agent at the url location 
      become: yes
      get_url: 
       url: https://getcomposer.org/installer
       dest: /tmp/installer
       mode: 0755

    - name: Install Composer  after grabbing it form the url
      become: yes
      shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
      args:
       creates: /usr/local/bin/composer
       
    - name: change the name of the composer install to just composer and put it in bin 
      become: yes 
      shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
      args: 
       creates: /usr/local/bin/composer
 
    - name: set composer to be usable 
      file:
       path: /usr/local/bin/composer
       mode: a+x
       state: file

 
    - name:  install the nginx conf and register it 
      become: yes
      copy: src=~/cit-360/ansible/web/nginx.conf dest=/etc/nginx/nginx.conf mode=0000
      register: nginx_conf

    - name: Configure vhost_conf and install the service 
      become: yes
      template: src=~/cit-360/ansible/web/vhost.conf.j2 dest=/etc/nginx/conf.d/{{ service_name }}.conf mode=0644
      register: vhost_conf

    - name: register php_conf and use it in the php.ini 
      become: yes
      template: src=~/cit-360/ansible/web/php.ini.j2 dest=/etc/php.ini mode=0644
      register: php_conf

    - name: register php_fpm_conf and put it in the www conf folder 
      become: yes
      copy: src=~/cit-360/ansible/web/php-fpm-web.conf dest=/etc/php-fpm.d/www.conf mode=0644
      register: php_fpm_conf

    - name: restart nginx 
      become: yes
      service: name=nginx state=restarted enabled=yes
      when: nginx_install|changed or nginx_conf|changed or vhost_conf|changed

    - name: restart php-fpm 
      become: yes
      service: name=php-fpm state=restarted enabled=yes
      when: nginx_install|changed or php_conf|changed or php_fpm_conf|changed

    - name: directory
      become: yes
      file: path={{ service_dir }}/ state=directory

    - name: unpack  the web stuff from the service directory
      become: yes
      unarchive: src=~/cit-360/ansible/web/{{ service_name }}.tgz dest="{{ service_dir }}"  mode=0755

    - name:  use composer to update service dir 
      become: yes
      command: /usr/local/bin/composer update chdir={{ service_dir }}
           

    - name:  change permissions
      become: yes
      file: recurse=yes path={{ service_dir }}/storage mode=0777

    - name: cahnge Permissions for nginx 
      become: yes
      file: recurse=yes path={{ service_dir }} owner=nginx group=nginx

    - name: install the template so website is viewable 
      become: yes
      template: src=~/cit-360/ansible/web/env.j2 dest="{{ service_dir }}/.env" mode=0644 owner=nginx
